version: '3'
services:
    listen:
        build: ../
        ports:
            - '80:80/tcp'
        volumes:
            - 'sqlite:./database/database.sqlite'
volumes:
    sqlite:
        driver: local
