version: '3'
services:
    listen:
        build: ../
        environment:
            APP_KEY: '${APP_KEY}'
        ports:
            - '80:80/tcp'
        volumes:
            - 'sqlite:/var/www/html/database/sqlite'
volumes:
    sqlite:
        driver: local
